// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MessageData struct {
	// shared between all requests
	ClientVersion        string   `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Gossip               bool     `protobuf:"varint,4,opt,name=gossip,proto3" json:"gossip,omitempty"`
	NodeId               string   `protobuf:"bytes,5,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodePubKey           []byte   `protobuf:"bytes,6,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

func (m *MessageData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MessageData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *MessageData) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type EmptyMessage struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}
func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (m *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(m, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

func (m *EmptyMessage) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageData)(nil), "protocols.core.MessageData")
	proto.RegisterType((*EmptyMessage)(nil), "protocols.core.EmptyMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x41, 0x4b, 0xf4, 0x30,
	0x10, 0x86, 0x49, 0x77, 0xbf, 0x7e, 0xee, 0x74, 0x77, 0x0f, 0x39, 0x48, 0x40, 0x91, 0xb2, 0x28,
	0xf6, 0xd4, 0x82, 0x9e, 0xbd, 0x88, 0x1e, 0x44, 0x16, 0xa4, 0x07, 0x0f, 0xde, 0xd2, 0x36, 0xc4,
	0xb0, 0x4d, 0x26, 0x24, 0xe9, 0x61, 0x7f, 0xa0, 0xff, 0x4b, 0x1a, 0x0b, 0xdb, 0x3d, 0x65, 0xe6,
	0xc9, 0xfb, 0x0e, 0x3c, 0xb0, 0xd1, 0xc2, 0x7b, 0x2e, 0x45, 0x69, 0x1d, 0x06, 0xa4, 0xdb, 0xf8,
	0xb4, 0xd8, 0xfb, 0xb2, 0x45, 0x27, 0x76, 0x3f, 0x04, 0xb2, 0xfd, 0x5f, 0xe2, 0x85, 0x07, 0x4e,
	0x6f, 0x61, 0xd3, 0xf6, 0x4a, 0x98, 0xf0, 0x29, 0x9c, 0x57, 0x68, 0x18, 0xc9, 0x49, 0xb1, 0xaa,
	0xcf, 0x21, 0xbd, 0x86, 0x55, 0x50, 0x5a, 0xf8, 0xc0, 0xb5, 0x65, 0x49, 0x4e, 0x8a, 0x45, 0x7d,
	0x02, 0x74, 0x0b, 0x89, 0xea, 0xd8, 0x22, 0x16, 0x13, 0xd5, 0xd1, 0x4b, 0x48, 0x25, 0x7a, 0xaf,
	0x2c, 0x5b, 0xe6, 0xa4, 0xb8, 0xa8, 0xa7, 0x6d, 0xe4, 0x06, 0x3b, 0xf1, 0xd6, 0xb1, 0x7f, 0x31,
	0x3b, 0x6d, 0xf4, 0x06, 0x60, 0x9c, 0x3e, 0x86, 0xe6, 0x5d, 0x1c, 0x59, 0x9a, 0x93, 0x62, 0x5d,
	0xcf, 0x08, 0xa5, 0xb0, 0xf4, 0x4a, 0x1a, 0xf6, 0x3f, 0xfe, 0xc4, 0x79, 0xb7, 0x87, 0xf5, 0xab,
	0xb6, 0xe1, 0x38, 0xb9, 0xd0, 0x27, 0xc8, 0xf4, 0x49, 0x2b, 0x5a, 0x64, 0x0f, 0x57, 0xe5, 0xb9,
	0x7d, 0x39, 0x33, 0xaf, 0xe7, 0xf9, 0xe7, 0xfb, 0xaf, 0x3b, 0xa9, 0xc2, 0xf7, 0xd0, 0x94, 0x2d,
	0xea, 0x8a, 0xf7, 0x78, 0x30, 0xc2, 0x0d, 0xee, 0xc0, 0x5d, 0x25, 0xd1, 0xb6, 0xb6, 0x1a, 0xeb,
	0x95, 0x6d, 0x9a, 0x34, 0x5e, 0x7c, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x33, 0xd2, 0x7b,
	0x67, 0x01, 0x00, 0x00,
}
