// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: heartbeat.proto

package pb

import (
	fmt "fmt"
	pb "github.com/aloknerurkar/gopcp/core/pb"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ServiceInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{0}
}
func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServiceInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type NodeInfo struct {
	IdBytes              []byte   `protobuf:"bytes,1,opt,name=id_bytes,json=idBytes,proto3" json:"id_bytes,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Updated              int64    `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{1}
}
func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetIdBytes() []byte {
	if m != nil {
		return m.IdBytes
	}
	return nil
}

func (m *NodeInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NodeInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type HeartbeatResp struct {
	MessageData          *pb.MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Services             []*ServiceInfo  `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	Updated              int64           `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HeartbeatResp) Reset()         { *m = HeartbeatResp{} }
func (m *HeartbeatResp) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResp) ProtoMessage()    {}
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{2}
}
func (m *HeartbeatResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResp.Unmarshal(m, b)
}
func (m *HeartbeatResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResp.Marshal(b, m, deterministic)
}
func (m *HeartbeatResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResp.Merge(m, src)
}
func (m *HeartbeatResp) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResp.Size(m)
}
func (m *HeartbeatResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResp.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResp proto.InternalMessageInfo

func (m *HeartbeatResp) GetMessageData() *pb.MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *HeartbeatResp) GetServices() []*ServiceInfo {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *HeartbeatResp) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func init() {
	proto.RegisterType((*ServiceInfo)(nil), "protocols.heartbeat.ServiceInfo")
	proto.RegisterType((*NodeInfo)(nil), "protocols.heartbeat.NodeInfo")
	proto.RegisterType((*HeartbeatResp)(nil), "protocols.heartbeat.HeartbeatResp")
}

func init() { proto.RegisterFile("heartbeat.proto", fileDescriptor_3c667767fb9826a9) }

var fileDescriptor_3c667767fb9826a9 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x55, 0x9a, 0x4f, 0x6d, 0x3e, 0x07, 0x84, 0x64, 0x04, 0x0a, 0xb0, 0x54, 0x99, 0x3a, 0xd9,
	0xa2, 0xac, 0xb0, 0x54, 0x0c, 0x30, 0xc0, 0xe0, 0x0e, 0x48, 0x2c, 0xc8, 0x4e, 0x8e, 0x34, 0x6a,
	0x93, 0xb3, 0x6c, 0xa7, 0x12, 0x7f, 0x88, 0xdf, 0x89, 0xe2, 0x34, 0x69, 0x06, 0x98, 0xec, 0xe7,
	0xbb, 0x7b, 0xef, 0xde, 0x33, 0x39, 0xdb, 0x80, 0x34, 0x4e, 0x81, 0x74, 0x4c, 0x1b, 0x74, 0x48,
	0xcf, 0xfd, 0x91, 0xe1, 0xce, 0xb2, 0xa1, 0x74, 0x7d, 0x91, 0xa1, 0x01, 0xae, 0x15, 0xaf, 0xc0,
	0x5a, 0x59, 0x40, 0xd7, 0x9b, 0xae, 0x49, 0xbc, 0x06, 0xb3, 0x2f, 0x33, 0x78, 0xae, 0x3f, 0x91,
	0x52, 0xf2, 0xaf, 0x96, 0x15, 0x24, 0xc1, 0x3c, 0x58, 0xfc, 0x17, 0xfe, 0x4e, 0x13, 0x32, 0xdb,
	0x83, 0xb1, 0x25, 0xd6, 0xc9, 0xc4, 0x3f, 0xf7, 0x90, 0x5e, 0x92, 0xa9, 0x75, 0xd2, 0x35, 0x36,
	0x09, 0x7d, 0xe1, 0x80, 0xd2, 0x37, 0x12, 0xbd, 0x62, 0xde, 0x31, 0x5e, 0x91, 0xa8, 0xcc, 0x3f,
	0xd4, 0x97, 0x03, 0xeb, 0x59, 0x4f, 0xc4, 0xac, 0xcc, 0x57, 0x2d, 0x1c, 0x8d, 0x4f, 0xc6, 0xe3,
	0xad, 0x60, 0xa3, 0x73, 0xe9, 0x20, 0xf7, 0xbc, 0xa1, 0xe8, 0x61, 0xfa, 0x1d, 0x90, 0xd3, 0xa7,
	0xde, 0x92, 0x00, 0xab, 0xe9, 0x03, 0x89, 0x0f, 0x86, 0x1e, 0xa5, 0x93, 0x5e, 0x21, 0x5e, 0xde,
	0xb0, 0x63, 0x02, 0xad, 0x6d, 0xf6, 0x72, 0x6c, 0x11, 0xe3, 0x7e, 0x7a, 0x4f, 0x22, 0xdb, 0xd9,
	0x6f, 0x97, 0x08, 0x17, 0xf1, 0x72, 0xce, 0x7e, 0x49, 0x8f, 0x8d, 0x32, 0x12, 0xc3, 0xc4, 0xdf,
	0x8b, 0xae, 0x6e, 0xdf, 0x79, 0x51, 0xba, 0x4d, 0xa3, 0x58, 0x86, 0x15, 0x97, 0x3b, 0xdc, 0xd6,
	0x60, 0x1a, 0xb3, 0x95, 0x86, 0x17, 0xa8, 0x33, 0xcd, 0xfd, 0x6f, 0x0c, 0xfc, 0x5c, 0x2b, 0x35,
	0xf5, 0xba, 0x77, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x00, 0x13, 0xe3, 0x8d, 0xcf, 0x01, 0x00,
	0x00,
}
